# Generated by Django 3.2.9 on 2021-11-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211116_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
